# NumPy

Adicionado a biblioteca numpy para computação cientificad

In [1]:
import numpy as np

# Operação e manipulação de arrays

In [2]:
# Array a partir de uma lista
array = np.array([1, 2, 3, 4])

# Array multidimensional
matriz = np.array([[1, 2], [3, 4]])


In [3]:
soma = array + 2
produto = array * 2

In [4]:
elemento = array[0]
subarray = matriz[:, 1]  # Segunda coluna da matriz


In [5]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

# Acessando elementos do índice 1 ao 4 (não inclusivo)
fatia = array[1:4]
print("Fatiamento:", fatia)  # Saída: [2 3 4]


Fatiamento: [2 3 4]


In [6]:
# Cópia
copia = array.copy()
copia[0] = 99
print("Original:", array)  # Saída: [1 2 3 4 5 6]
print("Cópia:", copia)    # Saída: [99 2 3 4 5 6]

# Visão
visao = array.view()
visao[0] = 99
print("Original após Visão:", array)  # Saída: [99 2 3 4 5 6]

Original: [1 2 3 4 5 6]
Cópia: [99  2  3  4  5  6]
Original após Visão: [99  2  3  4  5  6]


In [7]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Forma do array:", matriz.shape)  # Saída: (2, 3)

Forma do array: (2, 3)


In [8]:
array = np.array([1, 2, 3, 4, 5, 6])
matriz = array.reshape(2, 3)
print("Array Redimensionado:\n", matriz)
# Saída:
# [[1 2 3]
#  [4 5 6]]


Array Redimensionado:
 [[1 2 3]
 [4 5 6]]


In [9]:
for x in matriz:
    print("Linha:", x)
# Saída:
# Linha: [1 2 3]
# Linha: [4 5 6]

Linha: [1 2 3]
Linha: [4 5 6]


In [10]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
juncao = np.concatenate((array1, array2))
print("Arrays Juntos:", juncao)  # Saída: [1 2 3 4 5 6]


Arrays Juntos: [1 2 3 4 5 6]


In [11]:
array = np.array([1, 2, 3, 4, 5, 6])
divisao = np.array_split(array, 3)
print("Arrays Divididos:", divisao)
# Saída: [array([1, 2]), array([3, 4]), array([5, 6])]

Arrays Divididos: [array([1, 2]), array([3, 4]), array([5, 6])]


In [12]:
array = np.array([1, 2, 3, 4, 5])
indices = np.where(array > 3)
print("Índices onde array > 3:", indices)  # Saída: (array([3, 4]),)


Índices onde array > 3: (array([3, 4]),)


In [13]:
array = np.array([5, 2, 4, 1, 3])
ordenado = np.sort(array)
print("Array Ordenado:", ordenado)  # Saída: [1 2 3 4 5]


Array Ordenado: [1 2 3 4 5]


In [14]:
array = np.array([1, 2, 3, 4, 5])
filtro = array[array > 2]
print("Array Filtrado:", filtro)  # Saída: [3 4 5]


Array Filtrado: [3 4 5]


# UFuncs Comandos Comuns para Funções Universais 

In [15]:
soma = np.sum(array)
print(soma)

15


In [16]:
expo = np.exp(array)
print(expo)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [17]:
raiz = np.sqrt(array)
print(raiz)

[1.         1.41421356 1.73205081 2.         2.23606798]


# Funções com NumPy 

In [18]:

import numpy as np

def normaliza_array(arr):
    max_val = np.max(arr)
    min_val = np.min(arr)
    return (arr - min_val) / (max_val - min_val)


array = np.array([10,5])

print(normaliza_array(array))

[1. 0.]


# Arrays + NumPy

In [19]:
#media de alunos
import numpy as np

notas = np.array([7.5, 8.0, 6.5])
media = np.mean(notas)
print("Média das notas:", media)


Média das notas: 7.333333333333333


In [20]:
#preco com desconto

precos = np.array([50, 120, 30])
precos_com_desconto = precos * 0.9
print("Preços com desconto:", precos_com_desconto)

Preços com desconto: [ 45. 108.  27.]


In [21]:
# contagem de estoque

estoque = np.array([10, 5, 8, 3])
total = np.sum(estoque)
print("Total de itens em estoque:", total)

Total de itens em estoque: 26


In [22]:
#conversão de unidades
celsius = np.array([0, 20, 30, 40])
fahrenheit = (celsius * 9/5) + 32
print("Temperaturas em Fahrenheit:", fahrenheit)

Temperaturas em Fahrenheit: [ 32.  68.  86. 104.]
